name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6' # اختر نسخة Flutter المناسبة لمشروعك

    - name: Install dependencies
      run: flutter pub get

    - name: Run analyzer
      run: flutter analyze

    - name: Run tests
      run: flutter test

    # إذا أردت بناء apk
    - name: Build APK
      run: flutter build apk --release
      # يمكنك رفع ملف apk كـ artifact عند الحاجة
